### ISSUE TITLE
Add an init container to send mail when the Frontier Squid application has restarted

### ISSUE THREAD

**Issue by amblinalong** [slateci/atlas-squid#3]
From Lincoln:  Add an init container to send mail when the Frontier Squid application has restarted. I am imagining this being a generic thing.. Add the InitContainer with some Python or Bash code that pulls the MAILGUN_API_KEY out of the environment and sends an email letting the appropriate SLATE group know that there was an instance startup.

**Comment by cnweaver** [comment]
Whose Mailgun API key would this use? Putting a copy of SLATE's own API key on every cluster where any user runs an frontier squid sounds dangerous; it seems like it would be hard in particular to avoid leaking the key to the application owner(s) (e.g. if the key is stored in a secret, another application in the same namespace could just mount it and read it).

**Comment by LincolnBryant** [comment]
I'm going to close this issue - we ended up with a solution that uses an external service to send mails when the app restarts, based on liveness probes.
